"""empty message

Revision ID: b441e488714d
Revises: 4868780239ae
Create Date: 2019-12-08 14:12:50.600366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b441e488714d'
down_revision = '4868780239ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue', server_default=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue', server_default=None)
    # ### end Alembic commands ###
